import type {
  LlmGenerateRequest,
  LlmGenerateResponse,
  LlmProvider
} from "@/lib/llm/provider";

function extractPromptValue(prompt: string, label: string): string {
  const match = prompt.match(new RegExp(`${label}:\\s*(.+)`, "i"));

  return match?.[1]?.trim() ?? "";
}

export function createMockLlmProvider(): LlmProvider {
  return {
    name: "mock",
    modelName: "mock-editorial-enrichment-v0",
    isAvailable() {
      return { available: true };
    },
    async generate(request: LlmGenerateRequest): Promise<LlmGenerateResponse> {
      if (process.env.LLM_MOCK_RESPONSE) {
        return {
          text: process.env.LLM_MOCK_RESPONSE,
          providerName: "mock",
          modelName: "mock-editorial-enrichment-v0"
        };
      }

      const title =
        extractPromptValue(request.userPrompt, "Title") || "this technology signal";

      return {
        providerName: "mock",
        modelName: "mock-editorial-enrichment-v0",
        tokenUsage: {
          promptTokens: Math.ceil(request.userPrompt.length / 4),
          completionTokens: 180,
          totalTokens: Math.ceil(request.userPrompt.length / 4) + 180
        },
        text: JSON.stringify({
          whyItMatters: `${title} matters because it may change how teams evaluate, integrate, or govern emerging AI capabilities.`,
          whoShouldCare: ["AI engineer", "product builder", "technical manager"],
          technicalContext:
            "This is a mock LLM-assisted draft generated from the provided title, summary, tags, priority reasons, and related context.",
          impactAreas: ["developer tools", "agent workflow", "enterprise AI adoption"],
          learningPath: [
            "Read the original source to confirm the concrete change.",
            "Review the linked background knowledge before comparing implementation options.",
            "Map the signal to a small evaluation or pilot before broader adoption."
          ],
          relatedKnowledgeExplanations: {},
          relatedSkillExplanations: {},
          followUpQuestions: [
            `What real workflow would ${title} improve first?`,
            "What evidence would justify moving from tracking to piloting?",
            "Which risk or missing capability should be verified before adoption?"
          ],
          readingDifficulty: "intermediate",
          confidence: 0.72,
          limitations: [
            "Generated by the local mock provider; editor review is still required.",
            "The mock provider does not verify facts beyond the supplied draft inputs."
          ]
        })
      };
    }
  };
}
